HexaPestOtomasyon/Models/EnvanterModel.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using EntityLayer.Siniflar;

namespace HexaPestOtomasyon.Models
{
    public class EnvanterModel
    {
        public Pestisit Pestisits { get; set; }
        public Ekipman Ekipmans { get; set; }
      
        

    }

}

HexaPestOtomasyon/Models/MusteriModel.cs
using EntityLayer.Siniflar;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HexaPestOtomasyon.Models
{
    public class MusteriModel
    {
        public Musteri  Musteris { get; set; }
        public IEnumerable<SelectListItem> sehirler { get; set; }
        public IEnumerable<SelectListItem> ilceler { get; set; }
    }
}

HexaPestOtomasyon/Controllers/EnvanterController.cs
using DataAccessLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EntityLayer.Siniflar;
using HexaPestOtomasyon.Models;
using BusinessLayer;
using System.Data.Entity.Validation;
using System.Diagnostics;
using Serilog;
using System.Net;
using System.Threading.Tasks;

namespace HexaPestOtomasyon.Controllers
{
    public class EnvanterController : Controller
    {
        // GET: Envanter
        Context c = new Context();
        PestisitManager pm = new PestisitManager();
        EkipmanManager em = new EkipmanManager();
        public ActionResult Index()
        {
            var pest = c.Pestisits.Where(x => x.aktif == true).Count();

            int ekip = c.Ekipmans.Where(x => x.aktif == true).Count();

            ViewBag.pestisit = pest;
            ViewBag.ekipman = ekip;

            return View();

            
        }

        [HttpPost]
        public ActionResult pestisitEkle(EnvanterModel em)
        {

            //pm.pestisitEkle(em.Pestisits);
            c.Pestisits.Add(em.Pestisits);
            c.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult pestisitSil(int id)
        {
            pm.silPestisit(id);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult ekipmanEkle(EnvanterModel em)
        {
            c.Ekipmans.Add(em.Ekipmans);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult ekipmanSil(int id)
        {
            em.ekipmanSil(id);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
    }

}

HexaPestOtomasyon/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HexaPestOtomasyon.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

HexaPestOtomasyon/Controllers/MusteriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EntityLayer.Siniflar;
using BusinessLayer;
using DataAccessLayer;
using HexaPestOtomasyon.Models;

namespace HexaPestOtomasyon.Controllers
{
    public class MusteriController : Controller
    {
        // GET: Musteri
        Context c = new Context();
        SehirCascading sc = new SehirCascading();
        MusteriModel mm = new MusteriModel();
        MusteriManager ms = new MusteriManager();


        public ActionResult Index()
        {

            mm.sehirler = new SelectList(c.Sehirs, "ID", "sehirAdi");
            mm.ilceler = new SelectList(c.Ilces, "ID", "ilceAdi");




            return View(mm);
        }

        [HttpPost]
        public ActionResult musteriEkle(MusteriModel m)
        {
            c.Musteris.Add(m.Musteris);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public JsonResult ilceGetir(int p)
        {
            var ilceler = (from x in c.Ilces
                           join y in c.Sehirs on x.sehirID equals y.ID
                           where x.sehirID == p
                           select new
                           {
                               Text = x.ilceAdi,
                               Value = x.ilceAdi
                           }).ToList();
            return Json(ilceler, JsonRequestBehavior.AllowGet);
        }

        public ActionResult musteriDuzenle(MusteriModel m)
        {
            var musteri = c.Musteris.Find(m.Musteris.ID);

            if (string.IsNullOrEmpty(m.Musteris.sifre.ToString()))
            {

                musteri.ilce = m.Musteris.ilce;
                musteri.sehir = m.Musteris.sehir;
                musteri.sabitTel = m.Musteris.sabitTel;
                musteri.sabitTel2 = m.Musteris.sabitTel2;
                musteri.mobilTel = m.Musteris.mobilTel;
                musteri.mobilTel2 = m.Musteris.mobilTel2;
                musteri.adi = m.Musteris.adi;
                musteri.adres = m.Musteris.adres;
                musteri.firmaAdi = m.Musteris.firmaAdi;
            }
            else
            {

                musteri.ilce = m.Musteris.ilce;
                musteri.sehir = m.Musteris.sehir;
                musteri.sabitTel = m.Musteris.sabitTel;
                musteri.sabitTel2 = m.Musteris.sabitTel2;
                musteri.mobilTel = m.Musteris.mobilTel;
                musteri.mobilTel2 = m.Musteris.mobilTel2;
                musteri.sifre = m.Musteris.sifre;
                musteri.adi = m.Musteris.adi;
                musteri.adres = m.Musteris.adres;
                musteri.firmaAdi = m.Musteris.firmaAdi;
            }

            c.SaveChanges();
            return RedirectToAction("Index");


        }

        public ActionResult silMusteri(MusteriModel m)
        {
            ms.musteriSil(m.Musteris.ID);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

HexaPestOtomasyon/Controllers/PersonelController.cs
using BusinessLayer;
using DataAccessLayer;
using EntityLayer.Siniflar;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HexaPestOtomasyon.Controllers
{
    public class PersonelController : Controller
    {
        // GET: Personel
        Context c = new Context();
        PersonelManager pm = new PersonelManager();


        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult personelEkle(Personel p)
        {
            // pm.addPersonel(p);
            c.Personels.Add(p);
            c.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult personelSil(int id)
        {
            pm.silPersonel(id);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
    } 
}

HexaPestOtomasyon/Views/Deneme/Kaydet.cshtml
@model EntityLayer.Siniflar.Personel
@using BusinessLayer





@{
    ViewBag.Title = "Kaydet";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";


}

<br />

<br />
<link href="~/bootstrap-5.1.3-dist/css/bootstrap-grid.css" rel="stylesheet" />

@{

    PersonelManager pm = new PersonelManager();
}

<div class="container">
    <div class="card">
        <div class="card-header">

        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md">
                    <div class="card">
                        <div class="card-header bg-danger">
                            <i class="fas fa-street-view"></i>
                            Mesul Müdür
                        </div>
                        <div class="card-body">
                            <table class="table table-dark table-striped">

                                @foreach (var k in pm.GetAll())
                                {
                                    if (k.personelTip.ToString() == "Mesul Müdür" && k.aktif == true)
                                    {
                                        <tr>
                                            <td>@k.adi <a href="/Deneme/Sil/@k.ID" type="button" class="btn" style="background-color:transparent"><i class="fas fa-times-circle"/></a></td>
                                            
                                        </tr>
                                    }

                                }
                            </table>

                        </div>
                    </div>
                </div>
                <div class="col-md">
                    <div class="card">
                        <div class="card-header bg-danger">
                            <i class="fas fa-user-secret"></i>
                            Ekip Sorumlusu
                        </div>
                        <div class="card-body">

                            <table class="table table-dark table-striped">

                                @foreach (var k in pm.GetAll())
                                {
                                    if (k.personelTip.ToString() == "Ekip Sorumlusu" && k.aktif == true)
                                    {
                                        <tr>
                                            <td>@k.adi <a href="/Deneme/Sil/@k.ID" type="button" class="btn" style="background-color:transparent"><i class="fas fa-times-circle" /></a></td>
                                        </tr>
                                    }

                                }
                            </table>

                        </div>
                    </div>
                </div>
                <div class="col-md">
                    <div class="card">
                        <div class="card-header bg-danger">
                            Uygulayıcılar
                        </div>
                        <div class="card-body">
                            <table class="table table-dark table-striped">

                                @foreach (var k in pm.GetAll())
                                {
                                    if (k.personelTip.ToString() == "Uygulayıcı" && k.aktif == true)
                                    {
                                        <tr>
                                            <td>@k.adi <a href="/Deneme/Sil/@k.ID" type="button" class="btn" style="background-color:transparent"><i class="fas fa-times-circle" /></a></td>
                                        </tr>
                                    }

                                }
                            </table>
                        </div>
                    </div>
                </div>

            </div>
            <div class="row" style="text-align:center">
                <div class="col-md">
                    <button type="button" class="btn btn-outline-success" style="margin-top:20px; width:500px;" data-toggle="modal" data-target="#Modal1"><i class="fas fa-user-plus"></i> Personel Ekle</button>
                </div>
            </div>
        </div>
    </div>
</div>


@using (Html.BeginForm("Deneme", "Kaydet", FormMethod.Post))
{
    <div class="modal" id="Modal1">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">MODAL</h5>
                </div>
                <div class="modal-body">

                    <div class="input-group mb-3">
                        <span class="input-group-text" id="basic-addon1">İSİM SOYİSİM</span>
                        @*<input type="text" id="adi" name="adi" placeholder="İSİM" class="form-control" />*@
                        @Html.TextBoxFor(x => x.adi, new { @Class = "form-control" })
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="basic-addon1">TÜR</span>
                        @*<input type="text" id="tur" name="tur" placeholder="TÜR" class="form-control" />*@
                        @Html.DropDownListFor(x => x.personelTip, new List<SelectListItem> { new SelectListItem { Text="Mesul Müdür",Value="Mesul Müdür"},
                            new SelectListItem { Text="Uygulayıcı",Value="Uygulayıcı"},new SelectListItem { Text="Ekip Sorumlusu",Value="Ekip Sorumlusu"}}, new { @class = "form-control", id = "tur" })
                        @Html.HiddenFor(x => x.aktif, new { Value = true })
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Kapat</button>

                    @*<button id="kaydet" type="submit" class="btn btn-primary">Kaydet</button>*@
                    <input type="submit" class="btn btn-primary" name="save" value="Kaydet" formmethod="post" formaction="Kaydet" />




                </div>
            </div>
        </div>
    </div>
}

HexaPestOtomasyon/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

HexaPestOtomasyon/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

HexaPestOtomasyon/Views/Musteri/Index.cshtml
@using HexaPestOtomasyon.Models
@using BusinessLayer
@using EntityLayer.Siniflar
@model MusteriModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    MusteriManager mm = new MusteriManager();
    SehirManager sm = new SehirManager();
}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css">
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.bootstrap4.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap4.min.css">
<br />

<div class="container col-md-10">
    <div class="row">
        <div class="container">
            <div class="card">
                <div class="card-header bg-success">
                    <h5 style="text-align:center;color:white">MÜŞTERİ LİSTESİ</h5>
                </div>
                <div style="margin-top:20px;margin-left:10px;margin-right:10px">


                    <table id="musteri" class="table table-hover  table-striped  dt-responsive nowrap" style="width:100%;color:black;background-color:#ffffff">

                        <thead>
                            <tr>
                                <th>Müşteri Adı</th>
                                <th>Proje Sayısı</th>
                                <th>Hesap Durumu</th>
                                <th>Üyelik Tipi</th>
                                <th>İşlemler</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var x in mm.GetAll())
                            {

                                <tr>
                                    <td>@x.adi</td>
                                    <td>@x.projeSayisi</td>
                                    <td class="btn-success">
                                        @{string s = "";}
                                        @if (x.aktif == true)
                                        { s = "AKTİF"; }
                                        else
                                        {
                                            s = "PASİF";
                                        }
                                        @s
                                    </td>
                                    <td>@x.uyelikTip</td>
                                    <td><a href="/Envanter/pestisitSil/@x.ID" type="button" class="btn btn-outline-success"><i class="fas fa-trash-alt" />Görüntüle Ve Düzenle</a> <a href="/Envanter/pestisitSil/@x.ID" type="button" class="btn btn-outline-danger"><i class="fas fa-trash-alt" />SİL</a></td>

                                </tr>

                            }

                        </tbody>
                    </table>
                </div>
            </div>

        </div>

    </div>
    <div class="row" style="text-align:center">
        <div class="container">
            <button type="button" class="btn btn-outline-success" style="margin-top:20px; width:500px;" data-toggle="modal" data-target="#Modal1"><i class="fas fa-skull-crossbones"></i> Müşteri Ekle</button>
        </div>
    </div>
</div>
@using (Html.BeginForm("musteriEkle", "Musteri", FormMethod.Post))
{
    <div class="container">
        <div class="modal" id="Modal1">
            <div class="modal-dialog modal-dialog-scrollable modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Yeni Müşteri</h5>
                    </div>
                    <div class="modal-body">
                        <div class="btn-outline-success">

                            <h6>Yetkili ve Kullanıcı Bilgileri</h6>
                            <hr />
                        </div>

                        <div class="input-group mb-3">
                            <span class="input-group-text" id="basic-addon1">İSİM SOYİSİM</span>
                            @Html.TextBoxFor(x => x.Musteris.adi, new { placeholder = "Firma Yetkilisi ya da Şahıs Bilgisi", @Class = "form-control" })
                        </div>


                        <div>
                            <small style="color:black">  <i class="fa fa-info"></i>  Raporların Gönderileceği ve Giriş Yaparken Kullanılacak E-Posta</small>
                        </div>

                        <div class="input-group mb-3">
                            <span class="input-group-text" id="basic-addon1"><i class="fa fa-user"></i></span>

                            @Html.TextBoxFor(x => x.Musteris.mail, new { placeholder = "Örnek Hexa@Hexapest.com", @Class = "form-control" })
                        </div>
                        <div>
                            <small style="color:red">  <i class="fa fa-info"></i>  Geçici Şifre Kullanıcılardan Şifrelerini Değiştirmelerini İsteyiniz</small>
                        </div>
                        <div class="input-group mb-3">
                            <span class="input-group-text" id="basic-addon1"><i class="fas fa-user-lock"></i></span>
                            @Html.TextBoxFor(x => x.Musteris.sifre, new { placeholder = "ŞİFRE", @Class = "form-control",id="sifre" })
                        </div>
                        <div>
                            <small style="color:black">  <i class="fa fa-info"></i>  Yetkili Kişinin İrtibat Numaraları</small>
                        </div>
                        <div class="input-group mb-3">
                            <span class="input-group-text" id="basic-addon1"><i class="fa fa-phone"></i></span>
                            @Html.TextBoxFor(x => x.Musteris.sabitTel, new { placeholder = "Sabit Telefon", @Class = "form-control",id="sabitTel" })&emsp;

                            <span class="input-group-text" id="basic-addon1"><i class="	fa fa-mobile"></i></span>
                            @Html.TextBoxFor(x => x.Musteris.mobilTel, new { placeholder = "Mobil Telefon", @Class = "form-control",id="mobilTel" })

                        </div>

                        <div class="btn-outline-success">
                            <hr />
                            <h6>Hizmet Bölgesi Bilgileri</h6>
                            <hr />
                        </div>

                        <div class="input-group mb-3">
                            <span class="input-group-text" id="basic-addon1"><i class="fas fa-warehouse"></i></span>
                            @Html.TextBoxFor(x => x.Musteris.firmaAdi, new { placeholder = "Firma / Şahıs Adı", @Class = "form-control" })
                        </div>
                        <div class="input-group mb-3">
                            <span class="input-group-text" id="basic-addon1">Açık Adres</span>

                            @Html.TextAreaFor(x => x.Musteris.adres, new { @Class = "form-control" })
                        </div>
                        <div class="input-group mb-3">
                            <span class="input-group-text" id="basic-addon1">Şehir</span>
                            @Html.DropDownListFor(x => x.Musteris.sehir, Model.sehirler, "Şehir Seçiniz", new { @Class = "form-control", id = "DrpSehir" })&emsp;

                            <span class="input-group-text" id="basic-addon1">İlçe</span>
                            @Html.DropDownListFor(x => x.Musteris.ilce, Model.ilceler, "İlçe Seçiniz", new { @Class = "form-control", id = "DrpIlce" })
                            @Html.HiddenFor(x => x.Musteris.projeSayisi, new { Value = 0 })


                        </div>
                        <div class="input-group mb-3">
                            <span class="input-group-text" id="basic-addon1"><i class="fa fa-phone"></i></span>
                            @Html.TextBoxFor(x => x.Musteris.sabitTel2, new { placeholder = "Sabit Telefon", @Class = "form-control", id = "sabitTel2" })&emsp;

                            <span class="input-group-text" id="basic-addon1"><i class="	fa fa-mobile"></i></span>
                            @Html.TextBoxFor(x => x.Musteris.mobilTel2, new { placeholder = "Mobil Telefon", @Class = "form-control",id="mobilTel2" })
                            @Html.HiddenFor(x => x.Musteris.aktif, new { Value = true })

                        </div>



                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Kapat</button>

                        @*<button id="kaydet" type="submit" class="btn btn-primary">Kaydet</button>*@
                        <input type="submit" class="btn btn-primary" name="save" value="Kaydet" />




                    </div>
                </div>
            </div>
        </div>
    </div>
}
<script src="~/js/bootstrap.min.js"></script>
<script src="~/js/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/jquery.maskedinput.js"></script>
<script src="~/Scripts/jquery.maskedinput.min.js"></script>
<script>

    $(document).ready(function () {

        var table = $('#musteri').DataTable({

            lengthChange: true,
            pageLength: 5,
           
            "language": {

                "info": "Gösterilen Satırlar: _START_ ve _END_ Arasıdır. Toplam Veri : _TOTAL_ Satır",
                "infoEmpty": "Kayıt Bulunamadı",
                "search": "ARA:",
                "lengthMenu": "_MENU_ Satır",
                "zeroRecords": "HİÇ KAYIT YOK",
                "paginate": {
                    "previous": "Önceki",
                    "next":"Sonraki"
                }


            },
            "lengthMenu": [[5, 10, 25, 50, -1], [5, 10, 25, 50, "Tümü"]],




        });

        table.buttons().container()

            .appendTo('#example_wrapper .col-md-4:eq(0)');

    });

    $('#musteri td').hover(function () {
        $(this).css('color', 'green');
    },
        function () {
            $(this).css('color', 'black');
        });




</script>



<script>
    $(function () {
        $('#DrpSehir').change(function () {
            var id = $('#DrpSehir').val();
            $.ajax({
                url: '/Musteri/ilceGetir',
                data: { p: id },
                type: "POST",
                dataType: "Json",
                success: function (data) {
                    console.log(data);
                    $('#DrpIlce').empty();
                    for (var i = 0; i < data.length; i++) {
                        $('#DrpIlce').append("<option value='" + data[i].Value + "'>" + data[i].Text + "</Option>");
                    }
                }
            });
        });
    });
</script>

<script type="text/javascript">
    $('#sabitTel').mask('(999) 999-99-99');
    $('#sabitTel2').mask('(999) 999-99-99');
    $('#mobilTel').mask('(999) 999-99-99');
    $('#mobilTel2').mask('(999) 999-99-99');

</script>

HexaPestOtomasyon/Views/Personel/Index.cshtml
@model EntityLayer.Siniflar.Personel
@using BusinessLayer
@using GridMvc.Html





@{
    ViewBag.Title = "Kaydet";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";


}

<br />

<br />



@{

    PersonelManager pm = new PersonelManager();
}

<div class="container">
    <div class="card">
        <div class="card-header">

        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md">
                    <div class="card">
                        <div class="card-header bg-danger">
                            <i class="fas fa-street-view"></i>
                            Mesul Müdür
                        </div>
                        <div class="card-body">
                            <table class="table table-dark table-striped">

                                @foreach (var k in pm.GetAll())
                                {
                                    if (k.personelTip.ToString() == "Mesul Müdür" && k.aktif == true)
                                    {
                                        <tr>
                                            <td>@k.adi <a href="/Personel/personelSil/@k.ID" type="button" class="btn btn-outline-danger"><i class="fas fa-times-circle" /></a></td>

                                        </tr>
                                    }

                                }
                            </table>

                        </div>
                    </div>
                </div>
                <div class="col-md">
                    <div class="card">
                        <div class="card-header bg-danger">
                            <i class="fas fa-user-secret"></i>
                            Ekip Sorumlusu
                        </div>
                        <div class="card-body">

                            <table class="table table-dark table-striped">

                                @foreach (var k in pm.GetAll())
                                {
                                    if (k.personelTip.ToString() == "Ekip Sorumlusu" && k.aktif == true)
                                    {
                                        <tr>
                                            <td>@k.adi <a href="/Personel/personelSil/@k.ID" type="button" class="btn btn-outline-danger"><i class="fas fa-times-circle" /></a></td>
                                        </tr>
                                    }

                                }
                            </table>

                        </div>
                    </div>
                </div>
                <div class="col-md">
                    <div class="card">
                        <div class="card-header bg-danger">
                            <i class="fas fa-users"></i>
                            Uygulayıcılar
                        </div>
                        <div class="card-body">
                            <table class="table table-dark table-striped">

                                @foreach (var k in pm.GetAll())
                                {
                                    if (k.personelTip.ToString() == "Uygulayıcı" && k.aktif == true)
                                    {
                                        <tr>
                                            <td>@k.adi <a href="/Personel/personelSil/@k.ID" type="button" class="btn btn-outline-danger"><i class="fas fa-times-circle" /></a></td>
                                        </tr>
                                    }

                                }
                            </table>
                        </div>
                    </div>
                </div>

            </div>
            <div class="row" style="text-align:center">
                <div class="col-md">
                    <button type="button" class="btn btn-outline-success" style="margin-top:20px; width:500px;" data-toggle="modal" data-target="#Modal1"><i class="fas fa-user-plus"></i> Personel Ekle</button>
                </div>
            </div>
        </div>
    </div>
</div>


@using (Html.BeginForm("personelEkle","Personel",FormMethod.Post))
{
    <div class="modal" id="Modal1">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Personel Ekle</h5>
                </div>
                <div class="modal-body">

                    <div class="input-group mb-3">
                        <span class="input-group-text" id="basic-addon1">İSİM SOYİSİM</span>
                        @*<input type="text" id="adi" name="adi" placeholder="İSİM" class="form-control" />*@
                        @Html.TextBoxFor(x => x.adi, new { @Class = "form-control" })
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="basic-addon1">TÜR</span>
                        @*<input type="text" id="tur" name="tur" placeholder="TÜR" class="form-control" />*@
                        @Html.DropDownListFor(x => x.personelTip, new List<SelectListItem> { new SelectListItem { Text="Mesul Müdür",Value="Mesul Müdür"},
                            new SelectListItem { Text="Uygulayıcı",Value="Uygulayıcı"},new SelectListItem { Text="Ekip Sorumlusu",Value="Ekip Sorumlusu"}}, new { @class = "form-control", id = "tur" })
                        @Html.HiddenFor(x => x.aktif, new { Value = true })
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Kapat</button>

                    @*<button id="kaydet" type="submit" class="btn btn-primary">Kaydet</button>*@
                    <input type="submit" class="btn btn-primary" name="save" value="Kaydet" />




                </div>
            </div>
        </div>
    </div>
}





<script src="~/js/bootstrap.min.js"></script>
<script src="~/js/jquery-3.3.1.min.js"></script>